### ISSUE TITLE
[BUG] Safely remove openai = "1.30.5" as a dependency

### ISSUE THREAD

**Issue by vizsatiz** [rootflo/flo-ai#14]
**Describe the bug**
flo-ai doesnt need the openai dependency mentioned in the poetry file. Please remove it, see if all the examples are working and create a pull requesr

**Comment by mahiro72** [comment]
Hello @vizsatiz ,I'm interested in working on this issue. Would it be okay for me to pick it up?

**Comment by vizsatiz** [comment]
Yes please go ahead
