### ISSUE TITLE
 Incompatible Python Version Range for flo-ai Package

### ISSUE THREAD

**Issue by jacobsanosh** [rootflo/flo-ai#46]
While trying to install the flo-ai package using Poetry, I encountered a version compatibility error with Python. My project uses Python 3.11, which is within the supported range of flo-ai (>=3.10, <3.13). However, the dependency resolver fails, indicating that Python 3.11 should be compatible but is incorrectly considered incompatible.

[tool.poetry]
name = "flo-ai-demo"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.13"              ###it will work if you specify it like this### 
flo-ai = "^0.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

**Comment by vizsatiz** [comment]
Fixed by upgrading all library versions and increasing python support till `4.0`
