### ISSUE TITLE
[BUG] FloLLMRouter.Builder.init() got an unexpected keyword argument 'model_nick_name'

### ISSUE THREAD

**Issue by jacobsanosh** [rootflo/flo-ai#61]
**Describe the bug**
Issue while building teams

**To Reproduce**
1.TypeError: FloLLMRouter.Builder.__init__() got an unexpected keyword argument 'model_nick_name'

**Expected behavior**

**Screenshots**
If applicable, could you add screenshots to help explain your problem?

**Environment (please complete the following information):**
 - python version: [e.g. 3.11]
 - OS [e.g. windows, mac]
 - flo-ai version [e.g. 0.0.1]

**Additional context**

**Comment by vizsatiz** [comment]
Fixed in #62
